apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: nodejs-greeting-api
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: apps-gitops
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: contact@balen.dev
        name: flux
      messageTemplate: |
        Automated image update for nodejs-greeting-api

        {{range .Updated.Images}}
        {{println .}}
        {{end}}
    push:
      branch: main
  update:
    strategy: Setters
    path: "./apps/nodejs_greeting_api"
