apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: nodejs-greeting-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nodejs-greeting-api
  policy:
    alphabetical:
      order: asc
