apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: rails-greeting-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: rails-greeting-api
  policy:
    semver:
      range: "*"
